bodhi/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('bodhi.views',
    (r'^$', 'index'),
    (r'^pingall$', 'ping_all'),
    (r'^(\d+)/$', 'device'),
    (r'^(\d+)/ping$', 'device_ping'),
    (r'^(\d+)/wol$', 'device_wol'),
    (r'^(\d+)/pass$', 'device_ask_pass'),
    (r'^(\d+)/shutdown$', 'device_shutdown'),
    (r'^(\d+)/reboot$', 'device_shutdown'),
    (r'^(\d+)/img/(\d{1,2})$', 'history_image'),
)

urls.py
from django.conf.urls.defaults import *
from settings import DEBUG

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'lib.webpages.homepage'),
    (r'^help$', 'lib.webpages.help'),
    (r'^bodhi/', include('zenettic.bodhi.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

if DEBUG:
    urlpatterns += patterns('',
        (r'^styles/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': 'templates/styles'}),
        (r'^pix/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': 'templates/pix'}),
    )

zenettic/urls.py
from django.conf.urls.defaults import *
from settings import DEBUG

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'lib.webpages.homepage'),
    (r'^help$', 'lib.webpages.help'),
    (r'^bodhi/', include('bodhi.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

if DEBUG:
    urlpatterns += patterns('',
        (r'^styles/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': 'templates/styles'}),
        (r'^pix/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': 'templates/pix'}),
    )

bodhi/models.py
from django.db import models
from bodhi.choices import *

class Device(models.Model):
    """ Represent a network device """
    name = models.CharField(max_length=200)
    IP = models.IPAddressField(blank=True)
    MAC = models.CharField(max_length=18, blank=True)
    wakeup = models.BooleanField()
    shutdown = models.BooleanField()
    platform = models.CharField(max_length=10, blank=True)
    watt = models.IntegerField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]

class History(models.Model):
    """ History of a device """
    device = models.ForeignKey(Device)
    date = models.DateField(auto_now=True, db_index=True)
    timestamp = models.DateTimeField(auto_now=True, db_index=True)
    action = models.IntegerField(choices=ACTION_TYPES_CHOICES)
    user = models.TextField(max_length=20)
    result = models.IntegerField(choices=RESULTS_CODE, blank=True)
    comment = models.TextField(blank=True)

    def __unicode__(self):
        return self.device.name + ' ' + str(self.timestamp)

    class Meta:
        ordering = ["-timestamp"]
        get_latest_by = "timestamp"
        verbose_name_plural = "History"

bodhi/views.py
#!/usr/bin/python
""" Remotely manage network devices via webpages """

__docformat__ = 'epytext en'

######################################################################
## Imports
######################################################################
from bodhi.models import Device, History
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, redirect
from bodhi.choices import *
from django.db.models import Count
from django.core.exceptions import ObjectDoesNotExist

from lib.device import wake_on_lan, shutdown_win, shutdown_nix, ping
from lib.karma import Karma
from lib.graphs import history_img

from datetime import datetime, timedelta
from threading import Timer

######################################################################
## Views
######################################################################

def index(request):
    '''
    Homepage
    '''
    devices = Device.objects.all().order_by('name')
    history = []
    for device in devices :
        try:
          record = History.objects.filter(device=device).latest()
          history.append(record)
        except ObjectDoesNotExist :
          pass
    return render_to_response('bodhi/list.html', {'history': history})

def ping_all(request):
    '''
    Ping all devices
    '''

    devices = Device.objects.all().order_by('name')
    for dev in devices :
        hf = Karma()
        try:
          isUp=ping(dev.name)
        except Exception as e :
            hf.save(dev, 0, 1)
        else:
            hf.save(dev, 0, not isUp)
    return redirect(index)

def device(request, device_id):
    '''
    Display a device
    '''
    dev = get_object_or_404(Device, pk=device_id)
    last = History.objects.filter(device=device_id).latest()
    his = History.objects.filter(device=device_id).exclude(user='cron')[0:10]
    power = Device.objects.get(pk=device_id).watt
    today = datetime.today()
    kwh_today = History.objects.filter(device=device_id, action=0, user="cron", result=0, date=today).aggregate(Count('result'))["result__count"] * power / 1000.0
    yesterday = today - timedelta(days=1)
    kwh_day = History.objects.filter(device=device_id, action=0, user="cron", result=0, date=yesterday).aggregate(Count('result'))["result__count"] * power / 1000.0
    week = datetime.today() - timedelta(days=7)
    kwh_week = History.objects.filter(device=device_id, action=0, user="cron", result=0, date__gt=week).aggregate(Count('result'))["result__count"] * power / 1000.0
    img = history_img(device_id, 10)
    return render_to_response('bodhi/device.html',
                                {'device': dev,
                                'kwh_today' : kwh_today,
                                'kwh_day' : kwh_day,
                                'kwh_week': kwh_week,
                                'history' : his,
                                'img' : img,
                                'latest' : last})

def device_ping(request, device_id):
    '''
    Ping and display a device
    '''

    error_message = None
    dev = get_object_or_404(Device, pk=device_id)
    hf = Karma()
    try:
      isUp=ping(dev.name)
    except Exception as e :
        error_message = e.__unicode__()
        hf.save(dev, 0, 1)
    else:
        hf.save(dev, 0, not isUp)
    return redirect(device, device_id)

def device_wol(request, device_id):
    '''
    Wake up a device
    '''
    error_message = None
    dev = get_object_or_404(Device, pk=device_id)
    if dev.wakeup == False :
        error_message = "This device don't allow wakeups."
    else:
        hf = Karma()
        try:
            wake_on_lan(dev.MAC)
        except Exception as e:
            error_message = e.__unicode__()
            hf.save(dev, 1, 1)
        finally:
            hf.save(dev, 1, 0)
            t = Timer(180.0, device_ping, (request, device_id))
            t.start()
    last = History.objects.filter(device=device_id).latest()
    return render_to_response('bodhi/refresh.html',
                                {'device': dev,
                                'latest' : last,
                                'error_message' : error_message})

def device_ask_pass(request, device_id):
    '''
    Ask password for shutting down a device
    '''
    error_message = None
    dev = get_object_or_404(Device, pk=device_id)
    if dev.shutdown == False :
        error_message = "This device don't allow the shutdown."
        last = History.objects.filter(device=device_id).latest()
        return render_to_response('bodhi/refresh.html',
                                {'device': dev,
                                'latest' : last,
                                'error_message' : error_message})
    else:
        last = History.objects.filter(device=device_id).latest()
        power = Device.objects.get(pk=device_id).watt
        today = datetime.today()
        kwh_today = History.objects.filter(device=device_id, action=0, user="cron", result=0, date=today).aggregate(Count('result'))["result__count"] * power / 1000.0
        yesterday = today - timedelta(days=1)
        kwh_day = History.objects.filter(device=device_id, action=0, user="cron", result=0, date=yesterday).aggregate(Count('result'))["result__count"] * power / 1000.0
        week = datetime.today() - timedelta(days=7)
        kwh_week = History.objects.filter(device=device_id, action=0, user="cron", result=0, date=week).aggregate(Count('result'))["result__count"] * power / 1000.0
        kwh_gain = kwh_week - kwh_today

        if 'reboot' in request.GET and  request.GET["reboot"] == '1' :
            reboot = True
        else:
            reboot = False
        return render_to_response('bodhi/shutdown.html', {'latest': last,
                                                          'kwh_today' : kwh_today,
                                                          'kwh_day' : kwh_day,
                                                          'kwh_week': kwh_week,
                                                          'kwh_gain': kwh_gain,
                                                          'reboot': reboot})

def device_shutdown(request, device_id):
    '''
    Shutdown a device
    '''
    error_message = None
    dev = get_object_or_404(Device, pk=device_id)
    if dev.shutdown == False :
        error_message = "This device don't allow the shutdown."
    else:
        hf = Karma()
        if 'reboot' in request.POST and request.POST['reboot'] == 'on'  :
            action = 3
            reboot = True
        else:
            action = 2
            reboot = False
        try:
            if request.POST['timeout'] :
                timeout = int(request.POST['timeout'])
            else :
                timeout = 5
            if request.POST['password'] :
                password = request.POST['password']
            else :
                password = ''

            if dev.platform == "linux" :
                shutdown_nix(dev.name, request.POST['user'], password,
                             msg=request.POST['message'], reboot=reboot, timeout=timeout)
            else:
                shutdown_win(dev.name, request.POST['user'], password,
                             msg=request.POST['message'], reboot=reboot, timeout=timeout*60)
        except Exception as e:
            error_message = e.__unicode__()
            hf.save(dev, action, 1)
        finally:
            hf.save(dev, action, 0, request.POST['message'])
            t = Timer(180.0, device_ping, (request, device_id))
            t.start()
    last = History.objects.filter(device=device_id).latest()
    return render_to_response('bodhi/refresh.html',
                                {'device': dev,
                                'latest' : last,
                                'error_message' : error_message})

def history_image(request, device_id, days):

  return HttpResponse(history_img(device_id, days), mimetype='image/svg+xml')

templates/bodhi/device.html
{% extends "main.html" %}
{% load i18n %}
{% block main %}
  <div id="show">
      {% if not device %}
        <p>{% trans "No device in the DB." %}</p>
      {% else %}
        <h1>{{device.name}}</h1>
        {% if device.platform == 'linux' %}
            <img src="/pix/computer_linux.png" class="photo" alt="PC Linux" height="80" />
        {% else %}
          {% if device.platform == 'win32' %}
            <img src="/pix/computer_win32.png" class="photo" alt="PC Windows" height="80" />
          {% else %}
            <img src="/pix/computer.png" class="photo" alt="Mac" height="80" />
          {% endif %}
        {% endif %}
        <p>
        IP: {{ device.IP }}<br />
        MAC: {{ device.MAC }}
        </p>
        {% if latest.action == 0 %}
          {% if not latest.result %}
            <font color="green">{% trans "ON" %}</font>
          {% else %}
            <font color="blue">{% trans "OFF" %}</font>
          {% endif %}
        {% endif %}
        {% if latest.action == 1 %}
            {% trans "Wake UP" %}...
        {% endif %}
        {% if latest.action == 2 %}
            {% trans "Shutdown" %}...
        {% endif %}
        {% if latest.action == 3 %}
            {% trans "Rebooting" %}...
        {% endif %}
        <br />
        <font size="-1">{{latest.timestamp}}</font><br />
        <div class="action">
	  <a href="ping"><img src="/pix/icons/down.svg" alt=" P " height="32" /></a>
        {% if latest.action == 0 %}
          {% if latest.result %}
             <a href="wol"><img src="/pix/icons/reveil.svg" alt=" W " height="32" /></a>
          {% else %}
             <a href="pass"><img src="/pix/icons/shutdown.svg" alt=" S " height="32" /></a>
             <a href="pass?reboot=1"><img src="/pix/icons/restart.svg" alt=" R " height="32" /></a>
          {% endif %}
	{% endif %}
	</div>
      {% endif %}
      <h2>{% trans "Power consumption" %}</h2>
      {% trans "Power" %} : {{ device.watt }} Watt<br />
      {% trans "Today" %} : {{ kwh_today }} Kwh<br />
      {% trans "Yesterday" %} : {{ kwh_day }} Kwh<br />
      {% trans "Last week" %} : {{ kwh_week }} Kwh<br />
      <h2>{% trans "History" %}</h2>
      {% if not history %}
        <p>{% trans "No history in the DB." %}</p>
      {% else %}
        <h3>{% trans "10 last actions" %}</h3>
        {% for record in history %}
          {{ record.get_action_display }} @ {{ record.timestamp }} -> {{ record.get_result_display }}<br />
        {% endfor %}
      {% endif %}
      <h3>{% trans "Ping history" %}</h3>
      {{ img|safe }}
  </div>
{% endblock %}

templates/bodhi/list.html
{% extends "main.html" %}
{% load i18n %}
{% block head %}
    <title>Zen & TIC - Bodhi</title>
    <meta http-equiv="refresh" content="3600">
{% endblock %}
{% block main %}
  {% if not history %}
    <p>{% trans "No device in the DB." %}</p>
  {% else %}
    <div id="entrycontainer" class="clearfix">
    {% for device in history %}
    <div class="facelist_entry">
        <p class="title">{{device.device.name}}</p>
        <a href="{{device.device_id}}/">
        {% if device.device.platform == 'linux' %}
            <img src="/pix/computer_linux.png" align="left" class="photo" alt="PC Linux" height="80" />
        {% else %}
          {% if device.device.platform == 'win32' %}
            <img src="/pix/computer_win32.png" align="left" class="photo" alt="PC Windows" height="80" />
          {% else %}
            <img src="/pix/computer.png" align="left" class="photo" alt="Mac" height="80" />
          {% endif %}
        {% endif %}
        </a>
	{% if device.action == 0 %}
          {% if not device.result %}
            <font color="green">{% trans "ON" %}</font>
          {% else %}
            <font color="blue">{% trans "OFF" %}</font>
          {% endif %}
        {% endif %}
        {% if device.action == 1 %}
            {% trans "Wake UP" %} ...
        {% endif %}
        {% if device.action == 2 %}
            {% trans "Shutdown" %}...
        {% endif %}
        {% if device.action == 3 %}
            {% trans "Rebooting" %}...
        {% endif %}
        <br />
        <font size="-1">{{device.timestamp|timesince}}</font><br />
	<div class="action">
	    <a href="{{device.device_id}}/ping"><img src="/pix/icons/down.svg" alt=" P " height="32" /></a>
        </div>
    </div>
    {% endfor %}
    </div>
  {% endif %}
{% endblock %}

templates/bodhi/refresh.html
{% extends "main.html" %}
{% load i18n %}
{% block head %}
    <title>Zen&TIC - Bodhi</title>
    <meta http-equiv="refresh" content="180;url='/bodhi/{{device.id}}">
{% endblock %}
{% block main %}
  <div id="show">
      {% if not device %}
        <p>{% trans "No device in the DB." %}</p>
      {% else %}
        {% if device.platform == 'linux' %}
            <img src="/pix/computer_linux.png" align="left" class="photo" alt="PC Linux" height="80" />
        {% else %}
          {% if device.platform == 'win32' %}
            <img src="/pix/computer_win32.png" align="left" class="photo" alt="PC Windows" height="80" />
          {% else %}
            <img src="/pix/computer.png" align="left" class="photo" alt="Mac" height="80" />
          {% endif %}
        {% endif %}
        <h1><a href="/bodhi/{{device.id}}/">{{device.name}}</a></h1>
        <p>
        IP: {{ device.IP }}<br />
        MAC: {{ device.MAC }}
        </p>
        <center>
        <font size="+1">
        {% if latest.action == 0 %}
          {% if not latest.result %}
            <font color="green">{% trans "ON" %}</font>
          {% else %}
            <font color="blue">{% trans "OFF" %}</font>
          {% endif %}
        {% endif %}
        {% if latest.action == 1 %}
            {% trans "Wake UP" %}...
        {% endif %}
        {% if latest.action == 2 %}
            {% trans "Shutdown" %}...
        {% endif %}
        {% if latest.action == 3 %}
            {% trans "Rebooting" %}...
        {% endif %}
        </font>
        <br />
        <font size="-1">{{latest.timestamp}}</font><br />
        {% trans "Ping machine in 180 seconds..." %}
        </center>
      {% endif %}
  </div>
{% endblock %}

templates/bodhi/shutdown.html
{% extends "main.html" %}
{% load i18n %}
{% block main %}
  {% if not latest %}
    <p>Device not in the DB.</p>
  {% else %}
    <img src="/pix/computer.png" align="left" alt="computer" height="80" />
    <h1>{{latest.device.name}}</h1>
    <h3>{% trans "Consumption" %}</h3>
    {% trans "Today" %} : {{ kwh_today }} Kwh<br />
    {% trans "Day" %} - 1 : {{ kwh_day }} Kwh<br />
    {% trans "Day" %} - 7 : {{ kwh_week }} Kwh<br />
    {% trans "Gain" %} : {{ kwh_gain }} Kwh<br />
    <br />
    <h3>
      {% if reboot %}
        {% trans "Reboot" ? %}
      {% else %}
        {% trans "Shutdown" ? %}
      {% endif %}
    </h3>
    <form action="/bodhi/{{ latest.device.id }}/shutdown" method="post">
      <table>
      <tr>
        <td>{% trans "User" %}</td><td><input type="text" name="user" /></td>
      </tr>
      <tr>
        <td>{% trans "Password" %}</td><td><input type="password" name="password" /></td>
      </tr>
      <tr>
        <td>{% trans "Message" %}</td><td><input type="text" name="message" size='50'/></td>
      </tr>
      <tr>
        <td>{% trans "Timeout" %}</td><td><input type="text" name="timeout" value="5" size='5'> min.</td>
      </tr>
      <tr>
        <td>{% trans "Reboot" %}</td><td>
        {% if reboot %}
            <input type="checkbox" name="reboot" checked="checked" />
        {% else %}
            <input type="checkbox" name="reboot" />
        {% endif %}
        </td>
      </tr>
      </table>
      <input type="submit" value="Send" />
    </form>
    <form action="/bodhi/{{ device.device.id }}/" method="post">
        <input type="submit" value="Cancel" />
    </form>  {% endif %}
{% endblock %}